USE UITUNE

-- ACCOUNT --

INSERT INTO UserRole(displayname) VALUES(N'Admin')
INSERT INTO UserRole(displayname) VALUES(N'User')

INSERT INTO Users(displayname, username, password, IdRole) VALUES(N'ADMIN', N'admin', N'db69fc039dcbd2962cb4d28f5891aae1', 1)
INSERT INTO Users(displayname, username, password, IdRole) VALUES(N'USER1', N'user1', N'c3f38a9e7efe580f7b4ca6fec20ee2dd', 2)

-- ARTIST --
INSERT INTO Artist(artistName) VALUES (N'Sơn Tùng M-TP')
INSERT INTO Artist(artistName) VALUES (N'HIEUTHUHAI')
INSERT INTO Artist(artistName) VALUES (N'Miu Lê')
INSERT INTO Artist(artistName) VALUES (N'Tăng Duy Tân')
INSERT INTO Artist(artistName) VALUES (N'Văn Mai Hương')
INSERT INTO Artist(artistName) VALUES (N'Trung Quân')
INSERT INTO Artist(artistName) VALUES (N'Hoàng Thùy Linh')
INSERT INTO Artist(artistName) VALUES (N'Wren Evans')
INSERT INTO Artist(artistName) VALUES (N'LyLy')
INSERT INTO Artist(artistName) VALUES (N'Double2T')
INSERT INTO Artist(artistName) VALUES (N'Hòa Minzy')
INSERT INTO Artist(artistName) VALUES (N'B Ray')
INSERT INTO Artist(artistName) VALUES (N'Karik')
INSERT INTO Artist(artistName) VALUES (N'OnlyC')
INSERT INTO Artist(artistName) VALUES (N'Hà Nhi')
INSERT INTO Artist(artistName) VALUES (N'Khắc Việt')
INSERT INTO Artist(artistName) VALUES (N'Khắc Hưng')
INSERT INTO Artist(artistName) VALUES (N'Hoàng Tôn')
INSERT INTO Artist(artistName) VALUES (N'Justatee')
INSERT INTO Artist(artistName) VALUES (N'Phương Ly')
INSERT INTO Artist(artistName) VALUES (N'Phương Mỹ Chi')
INSERT INTO Artist(artistName) VALUES (N'Pháo')
INSERT INTO Artist(artistName) VALUES (N'AMEE')
INSERT INTO Artist(artistName) VALUES (N'tlinh')
INSERT INTO Artist(artistName) VALUES (N'Da LAB')
INSERT INTO Artist(artistName) VALUES (N'Hoàng Dũng')
INSERT INTO Artist(artistName) VALUES (N'Orange')
INSERT INTO Artist(artistName) VALUES (N'Mr.Siro')
INSERT INTO Artist(artistName) VALUES (N'Đức Phúc')
INSERT INTO Artist(artistName) VALUES (N'Erik')
INSERT INTO Artist(artistName) VALUES (N'Trúc Nhân')
INSERT INTO Artist(artistName) VALUES (N'Bích Phương')
INSERT INTO Artist(artistName) VALUES (N'MIN')
INSERT INTO Artist(artistName) VALUES (N'Binz')
INSERT INTO Artist(artistName) VALUES (N'Vũ.')
INSERT INTO Artist(artistName) VALUES (N'Đen')
INSERT INTO Artist(artistName) VALUES (N'Tóc Tiên')
INSERT INTO Artist(artistName) VALUES (N'Thùy Chi')
INSERT INTO Artist(artistName) VALUES (N'24k.Right')
INSERT INTO Artist(artistName) VALUES (N'MONO')

-- ALBUM --
INSERT INTO Album(title, artistID, release_year) VALUES (N'Making My Way (Single)', 1, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Muộn Rồi Mà Sao Còn (Single)', 1, 2021)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Chúng Ta Của Hiện Tại (Single)', 1, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Có Chắc Yêu Là Đây (Single)', 1, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Hãy Trao Cho Anh (Single)', 1, 2019)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Chạy Ngay Đi (Single)', 1, 2018)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Nơi Này Có Anh (Single)', 1, 2017)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Lạc Trôi (Single)', 1, 2017)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Chúng Ta Không Thuộc Về Nhau (Single)', 1, 2016)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Như Ngày Hôm Qua (Single)', 1, 2015)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Buông Đôi Tay Nhau Ra (Single)', 1, 2015)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Âm Thầm Bên Em (Single)', 1, 2015)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Chàng Trai Năm Ấy OST', 1, 2014)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Em Của Ngày Hôm Qua (EP)', 1, 2013)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Anh Sai Rồi (Single)', 1, 2013)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Cơn Mưa Ngang Qua (Single)', 1, 2011)

INSERT INTO Album(title, artistID, release_year) VALUES (N'Ai Cũng Phải Bắt Đầu Từ Đâu Đó', 2, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'ngủ một mình (tình rất tình) (Single)', 2, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Vệ Tinh (Single)', 2, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Nghe Như Tình Yêu (Single)', 2, 2021)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Lời Đường Mật (Single)', 2, 2020)

INSERT INTO Album(title, artistID, release_year) VALUES (N'Cô Đơn Đã Quá Bình Thường (Single)', 3, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Thầm Thương Trộm Nhớ (Single)', 3, 2021)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Giá Như Cô Ấy Chưa Xuất Hiện (Single)', 3, 2019)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Anh Đang Nơi Đâu (Single)', 3, 2016)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Quên Chưa Từng Yêu', 3, 2014)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Em Yêu Anh', 3, 2012)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Ngày Anh Xa', 3, 2011)

INSERT INTO Album(title, artistID, release_year) VALUES (N'Say Trong Nụ Cười (Single)', 4, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Cắt Đôi Nỗi Sầu (Single)',  4, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Bên Trên Tầng Lầu (Single)',  4, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Mắt Nâu (Single)',  4, 2021)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Ngây Thơ (Single)',  4, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'05 (Không Phai) (Single)',  4, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Tình Đầu (Single)',  4, 2020)

INSERT INTO Album(title, artistID, release_year) VALUES (N'Minh Tinh',  5, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Một Ngàn Nỗi Đau (Single)', 5, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'hương', 5, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Một Ngày Hay Trăm Năm (Single)', 5, 2018)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Mười Tám +', 5, 2013)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Nếu Như Anh Đến', 5, 2011)

INSERT INTO Album(title, artistID, release_year) VALUES (N'Những Câu Hỏi Khi Say (Single)', 6, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Bướm Mặt Trăng (EP)', 6, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Tình Nào Không Như Tình Đầu (Single)', 6, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Thánh Mưa', 6, 2014)

INSERT INTO Album(title, artistID, release_year) VALUES (N'LINK', 7, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Kiềng 3 Chân (Single)', 7, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Hoàng', 7, 2019)
INSERT INTO Album(title, artistID, release_year) VALUES (N'SIX', 7, 2016)

INSERT INTO Album(title, artistID, release_year) VALUES (N'Từng Quen (Single)', 8, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Call Me (Single)', 8, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Chiều Hôm Ấy Anh Thấy Màu Đỏ', 8, 2022)

INSERT INTO Album(title, artistID, release_year) VALUES (N'Lovely (EP)', 9, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Thất Tình Thương Hay Xấu Tính (Single)', 9, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Nếu Lỡ Một Ngày (Single)', 9, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Người Ta Đâu Thương Em (Single)', 9, 2021)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Bởi Vì Là Khi Yêu (Single)', 9, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Không Yêu Đừng Gây Thương Nhớ (Single)', 9, 2019)
INSERT INTO Album(title, artistID, release_year) VALUES (N'24H (Single)', 9, 2018)

INSERT INTO Album(title, artistID, release_year) VALUES (N'Chài Điếp Noọng (Anh Yêu Em) (Single)', 10, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'À Lôi (Single)', 10, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Người Miền Núi Chất (Single)', 10, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Tay - Lai Pr0 (Tây - Lai Pro) (Single)', 10, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Kéo Em Về Làm Vợ (Single)', 10, 2023)

INSERT INTO Album(title, artistID, release_year) VALUES (N'Thị Mầu (Single)', 11, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Bật Tình Yêu Lên (Single)',  11, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Người Đến Sau Thay Em (Single)', 11, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Bi Hài (Single)', 11, 2021)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Không Thể Cùng Nhau Suốt Kiếp (Single)', 11, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Chỉ Là Tình Cờ (Single)', 11, 2019)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Rời Bỏ (Single)', 11, 2018)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Nàng Tiên Cá (Single)', 11, 2018)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Chấp Nhận (Single)', 11, 2018)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Tìm Một Nửa Cô Đơn (Single)', 11, 2017)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Mưa Nhớ', 11, 2015)

INSERT INTO Album(title, artistID, release_year) VALUES (N'Anh Luôn Như Vậy (Single)', 12, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Bí Mật Nhỏ (Single)', 12, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Thói Quen (Single)', 12, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Thiêu Thân (Single)', 12, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Xin Đừng Nhấc Máy (Single)', 12, 2021)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Cao Ốc 20 (Single)', 12, 2019)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Yêu Như Trẻ Con (Single)', 12, 2019)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Ex''s Hate Me (Single)', 12, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Con Trai Cưng (Single)', 12, 2018)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Ở Trong Thành Phố (Single)', 12, 2017)

INSERT INTO Album(title, artistID, release_year) VALUES (N'Mời Người Kế Tiếp (Single)', 13, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Có Chơi Có Chịu (Single)', 13, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Vì Mẹ Anh Bắt Chia Tay (Single)', 13, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Người Lạ Ơi (Single)', 13, 2018)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Đòi Quà Cứ Ra Tòa (Single)', 13, 2027)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Anh Là Sinh Viên (Single)', 13, 2016)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Enjoy Your Life', 13, 2015)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Mixtape Back2Black', 13, 2010)

INSERT INTO Album(title, artistID, release_year) VALUES (N'Tuyệt Vời Đà Nẵng (Single)', 14, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Người Đáng Thương Là Anh (Single)', 14, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Có Lẽ Anh Chưa Từng (Single)', 14, 2021)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Đau Để Trưởng Thành (Single)', 14, 2019)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Quan Trọng Là Thần Thái (Single)', 14, 2018)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Yêu Đơn Phương (Single)', 14, 2018)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Yêu Là Tha Thu (Single)', 14, 2017)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Yêu Đi Đừng Sợ (Single)', 14, 2017)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Thấy Là Yêu Thương (Single)', 14, 2017)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Đếm Ngày Xa Em', 14, 2016)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Đắng Lòng Thanh Niên (Single)', 14, 2014)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Anh Không Đòi Quà (Single)', 14, 2013)


INSERT INTO Album(title, artistID, release_year) VALUES (N'Ai Lau Đôi Mi Hoen (Single)', 15, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Vì Em Chưa Bao Giờ Khóc (Single)', 15, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Mỹ Quyền (Single)', 15, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Hồi Kết (Single)', 15, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Lâu Lâu Nhắc Lại	(Single)', 15, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Chưa Quên Người Yêu Cũ (Single)', 15, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Lâu Phai (EP)', 15, 2021)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Từng Cho Nhau (Single)', 15, 2019)

INSERT INTO Album(title, artistID, release_year) VALUES (N'Chuyến Xe Cuộc Đời (Single)', 16, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Sau Này Chúng Ta Giàu (Single)', 16, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Em Lấy Chồng (Single)', 16, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Chạy Về Nơi Phía Anh (Single)', 16, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Suy Nghĩ Trong Anh (Single)', 16, 2021)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Hiện Đại (Single)', 16, 2021)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Khác Biệt (Single)', 16, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Không Phải Anh Đúng Không (Single)', 16, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Yêu Lại Từ Đầu (Single)', 16, 2019)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Không Yêu Cũng Đừng Làm Bạn', 16, 2015)

INSERT INTO Album(title, artistID, release_year) VALUES (N'Slower (Single)', 17, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'NGƯỜI LẠ TRONG MƠ (Single)', 17, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Em Có Hiểu Anh Không (Single)', 17, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Ta Vẫn Nắm Tay Nhau  (Single)', 17, 2021)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Chia Tay Đừng Làm Bạn (Single)', 17, 2018)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Tiền Đâu Mua Được (Single)', 17, 2017)

INSERT INTO Album(title, artistID, release_year) VALUES (N'emconnho ...? (Single)', 18, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Quan Tâm Em Mỗi Ngày (Single)', 18, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Tình Yêu Ngủ Quên (Single)', 18, 2021)
INSERT INTO Album(title, artistID, release_year) VALUES (N'I Love You So Much (Single)', 18, 2019)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Người Thương (Single)', 18, 2018)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Yêu Em Rất Nhiều (Single)', 18, 2017)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Chút Nắng Chút Mưa', 18, 2014)

INSERT INTO Album(title, artistID, release_year) VALUES (N'EZ Papa (Single)', 19, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Forget About Her (Single)', 19, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Em Không Lẻ Loi (Single)', 19, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Làm gì phải Hốt (Single)', 19, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'LUS (Single)', 19, 2019)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Thằng Điên (Single)', 19, 2018)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Đã Lỡ Yêu Em Nhiều (Single)', 19, 2017)
INSERT INTO Album(title, artistID, release_year) VALUES (N'1st Album Rn''B', 19, 2014)

INSERT INTO Album(title, artistID, release_year) VALUES (N'Little Love (But No Limit) (Single)', 20, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Anh Là Ngoại Lệ Của Em (Single)', 20, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Phiêu Nhịp Thở (Single)', 20, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'ThichThich (Single)', 20, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Missing You (Single)', 20, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Shine It Now - Thích Gì Làm Nấy (Single)', 20, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Anh Là Ai (Single)', 20, 2019)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Mặt Trời Của Em (Single)', 20, 2017)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Crush On You (Single)', 20, 2016)

INSERT INTO Album(title, artistID, release_year) VALUES (N'Đẩy Xe Bò (Single)', 21, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Vũ Trụ Có Anh (Single)', 20, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Chi? (EP)', 21, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Bát Nhã Tuyền', 21, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Thương Về Miền Trung', 21, 2017)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Quê Em Mùa Nước Lũ', 21, 2014)

INSERT INTO Album(title, artistID, release_year) VALUES (N'Một Ngày Chẳng Nắng (Single)', 22, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Kìa Bóng Dáng Ai (Single)', 22, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Nai Vàng (Single)', 22, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Độ Tộc 2 (Single)', 22, 2021)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Nói Dối (Single)', 22, 2021)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Lạy Ông Lạy Bà (Single)', 22, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'2 Phút Hơn (Single)', 22, 2020)

INSERT INTO Album(title, artistID, release_year) VALUES (N'Chủ nhật boy (Single)', 23, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'ưng quá chừng (Single)', 23, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Shay Nắng (Single)', 23, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'hai mươi hai (22) (Single)', 23, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'thay mọi cô gái yêu anh (Single)', 23, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Nói Hoặc Không Nói (Single)', 23, 2021)
INSERT INTO Album(title, artistID, release_year) VALUES (N'từ thích thích thành thương thương (Single)', 23, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Em Bé (Single)', 23, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'dreAMEE', 23, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Sao Anh Chưa Về Nhà (Single)', 23, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Trời Giấu Trời Mang Đi (Single)', 23, 2019)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Đen Đá Không Đường (Single)', 23, 2019)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Anh Nhà Ở Đâu Thế? (Single)', 23, 2019)

INSERT INTO Album(title, artistID, release_year) VALUES (N'ái', 24, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Gái Độc Thân (Single)', 24, 2021)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Chú Chó Trên Ô Tô (Single)', 24, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Mặc Sự Đời! (Single)', 24, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Tình Yêu Bận Bịu (Single)', 24, 2020)

INSERT INTO Album(title, artistID, release_year) VALUES (N'Kết Thúc Bắt Đầu (Single)', 25, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Từ Ngày Em Đến (Single)', 25, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'2 Ngày 1 Đêm (Single)', 25, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Chạy Khỏi Thế Giới Này (Single)', 25, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Thức Giấc (Single)', 25, 2021)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Gác Lại Âu Lo (Single)', 25, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Nước Mắt Em Lau Bằng Tình Yêu Mới (Single)', 25, 2019)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Thanh Xuân (Single)', 25, 2018)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Một Nhà (Single)', 25, 2015)

INSERT INTO Album(title, artistID, release_year) VALUES (N'yên (EP)', 26, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Nắng Thủy Tinh (Single)', 26, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Tôi Muốn Làm Cái Cây (Single)', 26, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Về Nghe Mẹ Ru (Single)', 26, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Yêu Xa Hóa Gần (Single)', 26, 2021)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Mùa Hè Bất Tận (Single)', 26, 2021)
INSERT INTO Album(title, artistID, release_year) VALUES (N'25', 26, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Tình Ca Hoàng Dũng', 26, 2018)

INSERT INTO Album(title, artistID, release_year) VALUES (N'Cuộc gọi về nhà (Single)', 27, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Có đau thì đau một mình (Single)', 27, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'7 tỷ người, tìm thấy anh rồi (Single)', 27, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Tự Sự (Single)', 27, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Em Hát Ai Nghe (Single)', 27, 2021)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Khi Em Lớn (Single)', 27, 2021)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Chân Ái (Single)', 27, 2020)

INSERT INTO Album(title, artistID, release_year) VALUES (N'Chẳng Ai Đến Thế Giới Này Để Cô Đơn (Single)', 28, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Mẹ Hiểu Con Không (Single)', 28, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Yêu Mấy Cũng Đừng Quay Lại (Single)', 28, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Anh Bước Ra Từ Manga (Single)', 28, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Phai Nhòa Cảm Xúc (Single)', 28, 2021)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Không Muốn Yêu Lại Càng Say Đắm (Single)', 28, 2021)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Yêu Người Không Thể Yêu (Single)', 28, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Cô Đơn Không Muốn Về Nhà (Single)', 28, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Đừng Lo Anh Đợi Mà (Single)', 28, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Một Bước Yêu Vạn Dặm Đau (Single)', 28, 2019)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Nước Mắt Và Em', 28, 2014)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Phải Chi Lúc Trước Anh Sai', 28, 2012)

INSERT INTO Album(title, artistID, release_year) VALUES (N'Em Đồng Ý (I Do) (Single)', 29, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Quá Khứ Đôi Hiện Tại Đơn (Single)', 29, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Ngày Đầu Tiên (Single)', 29, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Người Ơi Người Ở Đừng Về (Single)', 29, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Hơn Cả Yêu (Single)', 29, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Hết Thương Cạn Nhớ (Single)', 29, 2019)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Yêu Được Không (Single)', 29, 2019)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Còn Yêu, Đâu Ai Rời Đi (Single)', 29, 2018)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Vỡ (Single)', 29, 2018)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Ta Còn Yêu Nhau (Single)', 29, 2017)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Ánh Nắng Của Anh (Single)', 29, 2016)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Cũng Đành Thôi (Single)', 29, 2016)

INSERT INTO Album(title, artistID, release_year) VALUES (N'Thiên Tài (Single)', 30, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Là Mây Trên Bầu Trời Của Ai Đó (Single)', 30, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Đau Nhất Là Lặng Im (Single)', 30, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Chạy Về Khóc Với Anh (Single)', 30, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Anh Luôn Là Lý Do (Single)', 30, 2021)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Em Không Sai Chúng Ta Sai (Single)', 30, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Có Tất Cả Nhưng Thiếu Anh (Single)', 30, 2019)	
INSERT INTO Album(title, artistID, release_year) VALUES (N'Chạm Đáy Nỗi Đau (Single)', 30, 2018)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Mình Chia Tay Đi (Single)', 30, 2018)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Ghen (Single)', 30, 2017)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Sau Tất Cả (Single)', 30, 2016)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Lạc Nhau Có Phải Muôn Đời (Single)', 30, 2016)

INSERT INTO Album(title, artistID, release_year) VALUES (N'Chạm Gần Thêm Thương (Single)', 31, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Vẽ Đường Cong (Single)', 31, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Có Không Giữ Mất Đừng Tìm (Single)', 31, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Sáng Mắt Chưa? (Single)', 31, 2019)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Lớn Rồi Còn Khóc Nhè (Single)', 31, 2019)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Người Ta Có Thương Mình Đâu (Single)', 31, 2018)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Ngồi Hát Đỡ Buồn (Single)', 31, 2017)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Making Money', 31, 2016)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Muốn Khóc Thật To (Single)', 31, 2015)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Tìm (Single)', 31, 2014)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Vẽ (Single)', 31, 2014)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Bốn Chữ Lắm (Single)', 31, 2014)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Đông (Single)', 31, 2013)

INSERT INTO Album(title, artistID, release_year) VALUES (N'Đưa Em Đi Khắp Thế Gian (Single)', 32, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'nhạc liu riu (EP)', 32, 2021)
INSERT INTO Album(title, artistID, release_year) VALUES (N'tâm trạng tan hơi chậm một chút (EP)', 32, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Đi Đu Đưa Đi (Single)', 32, 2019)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Chuyện Cũ Bỏ Qua (Single)', 32, 2018)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Bùa Yêu (Single)', 32, 2018)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Chị Ngã Em Nâng (Single)', 32, 2018)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Nói Thương Nhau Thì Đừng Làm Trái Tim Em Đau (Single)', 32, 2017)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Bao Giờ Lấy Chồng? (Single)', 32, 2017)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Gửi Anh Xa Nhớ (Single)', 32, 2016)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Rằng Em Mãi Ở Bên', 32, 2015)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Điều Chưa Từng Nói', 32, 2014)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Mình Yêu Nhau Đi (Single)', 32, 2014)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Chỉ Là Em Giấu Đi', 32, 2013)

INSERT INTO Album(title, artistID, release_year) VALUES (N'Tìm X (Single)', 33, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'50/50', 33, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Hít Vào Thở Ra (Single)', 33, 2021)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Trên Tình Bạn Dưới Tình Yêu (Single)', 33, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Đừng Yêu Nữa, Em Mệt Rồi (Single)', 33, 2019)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Vì Yêu Cứ Đâm Đầu (Single)', 33, 2019)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Em Mới Là Người Yêu Anh (Single)', 33, 2018)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Có Em Chờ (Single)', 33, 2017)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Chưa Bao Giờ Mẹ Kể (Single)', 33, 2017)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Hôn Anh (Single)', 33, 2017)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Gọi Tên Em (Single)', 33, 2016)

INSERT INTO Album(title, artistID, release_year) VALUES (N'Đan Xinh In Love (EP)', 34, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Don''t Break My Heart (Single)', 34, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Cho Mình Em (Single)', 34, 2021)
INSERT INTO Album(title, artistID, release_year) VALUES (N'ToGetHer (Single)', 34, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'021 (Single)', 34, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Bigcityboi (Single)', 34, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'OK (Single)', 34, 2019)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Quên Anh Đi (Single)', 34, 2019)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Sao Cũng Được (Single)', 34, 2018)
INSERT INTO Album(title, artistID, release_year) VALUES (N'SOFAR (Single)', 34, 2018)

INSERT INTO Album(title, artistID, release_year) VALUES (N'Một Vạn Năm', 35, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Happy For You (Single)', 35, 2021)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Bước Qua Nhau (Single)', 35, 2021)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Bước Qua Mùa Cô Đơn (Single)', 35, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Đã Từng Là (Single)', 35, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Một Giấc Mơ (Single)', 35, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Mùa Hè Của Em (Single)', 35, 2019)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Xin Phép Được Cô Đơn (Single)', 35, 2019)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Có thể là tại sao? (Single)', 35, 2019)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Lạ Lùng (Single)', 35, 2016)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Đông Kiếm Em (Single)', 35, 2016)

INSERT INTO Album(title, artistID, release_year) VALUES (N'Nấu ăn cho em (Single)', 36, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Luôn yêu đời (Single)', 36, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Ai muốn nghe không (Single)', 36, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Mang Tiền Về Cho Mẹ (Single)', 36, 2021)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Trốn Tìm (Single)', 36, 2021)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Đi Về Nhà (Single)', 36, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Trời hôm nay nhiều mây cực! (Single)', 36, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'một triệu like (Single)', 36, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Lối Nhỏ (Single)', 36, 2019)
INSERT INTO Album(title, artistID, release_year) VALUES (N'hai triệu năm (Single)', 36, 2019)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Bài Này Chill Phết (Single)', 36, 2019)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Mười Năm (Single)', 36, 2019)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Đố em biết anh đang nghĩ gì (Single)', 36, 2018)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Anh Đếch Cần Gì Nhiều Ngoài Em (Single)', 36, 2018)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Đưa Nhau Đi Trốn (Single)', 36, 2015)

INSERT INTO Album(title, artistID, release_year) VALUES (N'CONG', 37, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Yêu Rồi Yêu Rồi Yêu (EP)', 37, 2021	)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Em Đã Có Người Mới (Single)', 37, 2021)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Ngày Tận Thế (Single)', 37, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Thì Em Vẫn Thế (Single)', 37, 2018)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Phút Giây Tuyệt Vời (Single)', 37, 2018)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Có Ai Thương Em Như Anh (#CATENA) (Single)', 37, 2018)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Hôm Nay Tôi Cô Đơn Quá (Single)', 37, 2017)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Em Không Là Duy Nhất (Single)', 37, 2017)

INSERT INTO Album(title, artistID, release_year) VALUES (N'OST Người Vợ Cuối Cùng', 38, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Nếu Nỗi Buồn Là Một Bông Hoa (Single)', 38, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Hơn Em Chỗ Nào (Single)', 38, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Việt Nam Trong Tôi Là (Tí Nâu) (Single)', 38, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Thong Dong Mà Hát', 38, 2022)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Phiến Lá Tĩnh Lặng (Single)', 38, 2021)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Giấc Mơ Trưa (Single)', 38, 2020)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Mùa Hạ Ơi Xa Rồi (Single)', 38, 2019)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Những Đứa Con Xa Nhà (Single)', 38, 2018)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Mình Cùng Nhau Đóng Băng (Single)', 38, 2018)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Nàng Thơ Xứ Huế (Single)', 38, 2018)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Cha Và Con Gái (Single)', 38, 2017)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Xe Đạp (Single)', 38, 2015)

INSERT INTO Album(title, artistID, release_year) VALUES (N'Nội Dung Nhạy Cảm - Part 1 (EP)', 39, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Vẫn (Single)', 39, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Truy Lùng Bảo Vật (Single)', 39, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Từ A đến Z (Single)', 39, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Bao Giờ Lấy Vợ (Single)', 39, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Bao Giờ Em Đổ (Single)', 39, 2019)

INSERT INTO Album(title, artistID, release_year) VALUES (N'Stay Cool 2 (Single)', 40, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Người Tình Mùa Đông (DTAP) (Single)', 40, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'Stay Cool (Single)', 40, 2023)
INSERT INTO Album(title, artistID, release_year) VALUES (N'22', 40, 2022)

-- Song --
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Making My Way', 1, '00:04:18', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Muộn Rồi Mà Sao Còn', 2, '00:04:36', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chúng Ta Của Hiện Tại', 3, '00:05:02', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Có Chắc Yêu Là Đây', 4, '00:03:35', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Hãy Trao Cho Anh', 5, '00:04:06', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chạy Ngay Đi', 6, '00:04:08', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Nơi Này Có Anh', 7, '00:04:22', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Lạc Trôi', 8, '00:03:53', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chúng Ta Không Thuộc Về Nhau', 9, '00:03:53', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Như Ngày Hôm Qua', 10, '00:03:42', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Buông Đôi Tay Nhau Ra', 11, '00:03:46', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Âm Thầm Bên Em', 12, '00:04:51', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chắc Ai Đó Sẽ Về', 13, '00:04:54', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Không Phải Dạng Vừa Đâu', 13, '00:04:06', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Em Của Ngày Hôm Qua', 14, '00:03:52', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Nắng Ấm Xa Dần', 14, '00:03:10', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Anh Sai Rồi', 15, '00:04:22', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Cơn Mưa Ngang Qua', 16, '00:03:54', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Ai Cũng Phải Bắt Đầu Từ Đâu Đó', 17, '00:02:18', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Giờ Thì Ai Cười', 17, '00:03:07', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Không Phải Gu', 17, '00:03:21', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Siêu Sao', 17, '00:03:07', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Giờ Thì Ai Cười', 17, '00:03:07', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Đi Họp Lớp', 17, '00:02:48', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Không Thể Say', 17, '00:03:48', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Exit Sign', 17, '00:03:22', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Visa Interlude', 17, '00:00:41', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Sắp Nổi Tiếng', 17, '00:03:42', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'KPI', 17, '00:03:29', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Everything Will Be Okay', 17, '00:03:19', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Cho Em An Toàn', 17, '00:03:51', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'NOLOVENOLIFE', 17, '00:02:51', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'ngủ một mình', 18, '00:03:01', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Vệ Tinh', 19, '00:03:39', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Nghe Như Tình Yêu', 20, '00:03:13', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Lời Đường Mật', 21, '00:03:42', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Cô Đơn Đã Quá Bình Thường', 22, '00:04:38', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Thầm Thương Trộm Nhớ', 23, '00:03:03', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Giá Như Cô Ấy Chưa Xuất Hiện', 24, '00:05:10', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Anh Đang Nơi Đâu', 25, '00:03:21', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Quên Như	Chưa Từng Yêu', 26, '00:04:31', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Bức Tranh Trong Tim', 26, '00:03:59', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Không Còn Nước Mắt', 26, '00:04:16', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Tiếng Dương Cầm Trong Đêm', 26, '00:04:22', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Nơi Em Chờ Anh', 26, '00:06:10', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'My Boy', 27, '00:03:59', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Con Tim Mong Manh', 27, '00:04:52', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Yêu Anh', 27, '00:04:19', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Em Yêu Anh (I Love You)', 27, '00:03:39', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Ngày Anh Xa', 28, '00:04:18', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Em Nhớ Anh', 28, '00:03:45', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Giấc Mơ Thần Tiên', 28, '00:04:05', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Say Trong Nụ Cười', 29, '00:04:08', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Cắt Đôi Nỗi Sầu', 30, '00:03:02', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Bên Trên Tầng Lầu', 31, '00:03:04', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Mắt Nâu', 32, '00:04:52', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Ngây Thơ', 33, '00:04:13', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'05 (Không Phai)', 34, '00:03:09', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Tình Đầu', 35, '00:04:58', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Đại Minh Tinh', 36, '00:04:07', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Martini', 36, '00:03:20', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Vườn Địa Đàng', 36, '00:03:08', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'A Red Flag', 36, '00:03:51', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Bay Cùng Bay', 36, '00:04:13', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Mưa Tháng Sáu', 36, '00:04:17', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Cơn Mưa Rào', 36, '00:03:45', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Nam Bán Cầu', 36, '00:03:18', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Một Ngàn Nỗi Đau', 37, '00:05:22', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Đốt', 38, '00:04:23', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Cầu Hôn', 38, '00:04:04', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Tình Lãng Phí', 38, '00:04:17', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Đã Lâu Lắm Rồi', 38, '00:03:38', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Trên Cây Cầu Bên Sông', 38, '00:05:00', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Nghe Nói Anh Sắp Kết Hôn Rồi', 38, '00:04:17', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Mai Đây Em Thương Một Chàng Trai', 38, '00:04:11', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Hương', 38, '00:03:30', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Một Ngày Hay Trăm Năm', 39, '00:04:47', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chậm Lại Một Phút', 40, '00:04:58', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Riêng Mình Anh Thôi', 40, '00:04:06', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Giấc Mơ Thức Tỉnh', 40, '00:04:07', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Ngày Em 18', 40, '00:03:50', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Anh Mang Theo Mùa Xuân', 40, '00:04:11', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chuyện Tình Nhà Thơ', 40, '00:03:29', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Tango Trao Em', 40, '00:03:14', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Nếu Như Anh Đến', 41, '00:03:33', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Đừng Ngồi Yên Trong Góc Tối', 41, '00:03:13', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Trôi Trong Gương', 41, '00:03:20', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Những Câu Hỏi Khi Say', 42, '00:04:24', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Và Ngày Nào Đó', 43, '00:04:22', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Tự Tình 2', 43, '00:04:51', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Buồn Không Thể Buông', 43, '00:04:15', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Nguyệt Thượng Hạ Lưu', 43, '00:04:15', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Tình Nào Không Như Tình Đầu', 44, '00:04:42', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Thả Vào Mưa', 45, '00:05:43', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Dấu Mưa', 45, '00:04:20', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chuyện Mưa', 45, '00:04:20', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Sau Cơn Mưa', 45, '00:04:50', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chiều Nay Không Có Mưa Bay', 45, '00:04:56', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Gọi Mưa', 45, '00:05:50', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Xin Mưa Rơi Nhanh', 45, '00:04:57', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Mưa Trên Biển Vắng', 45, '00:04:08', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Gieo Quẻ', 46, '00:03:19', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'See Tình', 46, '00:03:05', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Lúc Thấy Lúc Không', 46, '00:02:53', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Bắt Vía', 46, '00:03:24', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'không một bài hát nào có thể diễn tả cảm xúc của em lúc này.', 46, '00:04:01', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Bo Xì Bo', 46, '00:02:52', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Trưởng Nữ Chạy Trốn', 46, '00:03:15', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Đánh Đố', 46, '00:04:28', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Hạ Phỏm', 46, '00:03:16', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Kiềng 3 Chân', 47, '00:03:16', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Khởi Đầu', 48, '00:00:34', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Để Mị Nói Cho Mà Nghe', 48, '00:03:19', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Duyên Âm', 48, '00:02:59', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Em Đây Chẳng Phải Thúy Kiều', 48, '00:03:34', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Lắm Mối Tối Ngồi Không', 48, '00:03:14', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Kẽo Cà Kẽo Kẹt', 48, '00:03:15', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Tứ Phủ', 48, '00:04:24', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Kẻ Cắp Gặp Bà Già', 48, '00:03:51', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Giải Kết', 48, '00:03:19', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'I''m Gonna Break', 49, '00:04:25', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Bánh Trôi Nước', 49, '00:04:27', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'London Bridge', 49, '00:04:16', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Từng Quen', 50, '00:02:55', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Call Me', 51, '00:03:35', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chiều Hôm Ấy (Intro)', 52, '00:01:11', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Cơn Đau', 52, '00:03:39', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Anh Thấy (Interlude)', 52, '00:00:38', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Gặp May', 52, '00:03:07', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Thích Em Hơi Nhiều', 52, '00:02:52', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Trao', 52, '00:03:12', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Màu Đỏ (Interlude)', 52, '00:01:04', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Mấy Khi', 52, '00:02:29', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Ngủ Đông', 53, '00:03:03', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Cho Em Xin Lỗi Đi Mà', 53, '00:03:49', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Tình Yêu So Cute', 53, '00:03:07', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Tại Sao Anh Nhận Lời', 53, '00:03:43', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Sau Cơn Mưa Trời Lại Sáng', 53, '00:03:41', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Thất Tình Thường Xấu Tính', 54, '00:03:32', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Nếu Lỡ Một Ngày', 55, '00:02:37', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Người Ta Đâu Thương Em', 56, '00:04:34', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Bởi Vì Là Khi Yêu', 57, '00:04:12', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Không Yêu Đừng Gây Thương Nhớ', 58, '00:04:42', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'24H', 59, '00:04:17', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chài Điếp Noọng (Anh Yêu Em)', 60, '00:04:18', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'À Lôi', 61, '00:03:17', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Người Miền Núi Chất', 62, '00:04:00', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Tay - Lai Pr0 (Tây - Lai Pro)', 63, '00:04:18', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Kéo Em Về Làm Vợ', 64, '00:03:20', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Thị Mầu', 65, '00:03:25', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Bật Tình Yêu Lên', 66, '00:03:24', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Người Đến Sau Thay Em', 67, '00:05:09', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Bi Hài', 68, '00:05:17', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Không Thể Cùng Nhau Suốt Kiếp', 69, '00:05:01', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chỉ Là Tình Cờ', 70, '00:04:39', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Rời Bỏ', 71, '00:04:37', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Nàng Tiên Cá', 72, '00:03:32', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chấp Nhận', 73, '00:04:07', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Tìm Một Nửa Cô Đơn', 74, '00:05:20', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Mưa Nhớ', 75, '00:04:00', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Gửi', 75, '00:04:45', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Thư Chưa Gửi Anh', 75, '00:03:28', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Anh Luôn Như Vậy', 76, '00:03:33', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Bí Mật Nhỏ', 77, '00:03:54', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Thói Quen', 78, '00:03:22', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Thiêu Thân', 79, '00:03:19', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Xin Đừng Nhấc Máy', 80, '00:03:07', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Cao Ốc 20', 81, '00:04:14', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Yêu Như Trẻ Con', 82, '00:03:26', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Ex''s Hate Me', 83, '00:03:51', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Con Trai Cưng', 84, '00:02:38', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Ở Trong Thành Phố', 85, '00:03:05', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Mời Người Kế Tiếp', 86, '00:03:12', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Có Chơi Có Chịu', 87, '00:03:44', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Vì Mẹ Anh Bắt Chia Tay', 88, '00:04:22', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Người Lạ Ơi', 89, '00:03:37', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Đòi Quà Cứ Ra Tòa', 90, '00:04:01', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Anh Là Sinh Viên', 91, '00:03:49', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Enjoy Your Life', 92, '00:03:29', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Làm Sao Đây', 92, '00:03:20', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Anh Là Của Em', 92, '00:03:36', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Tao Biết', 93, '00:01:31', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Người Ngoài Cuộc', 93, '00:03:26', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Không Thể 2', 93, '00:02:46', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'3 Thằng Bạn', 93, '00:03:47', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Trả Giá', 93, '00:02:49', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Back 2 Black', 93, '00:03:54', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Tuyệt Vời Đà Nẵng', 94, '00:03:38', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Người Đáng Thương Là Anh', 95, '00:04:52', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Có Lẽ Anh Chưa Từng', 96, '00:04:55', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Đau Để Trưởng Thành', 97, '00:04:43', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Quan Trọng Là Thần Thái', 98, '00:04:00', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Yêu Đơn Phương', 99, '00:04:29', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Yêu Là Tha Thu', 100, '00:04:33', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Yêu Đi Đừng Sợ', 101, '00:05:16', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Thấy Là Yêu Thương', 102, '00:04:02', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Giá Như Anh Lặng Im', 103, '00:04:11', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Đếm Ngày Xa Em', 103, '00:04:17', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Em Có Yêu Anh Không', 103, '00:03:38', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Đắng Lòng Thanh Niên', 104, '00:03:35', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Anh Không Đòi Quà', 105, '00:02:47', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Ai Lau Đôi Mi Hoen', 106, '00:03:35', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Vì Em Chưa Bao Giờ Khóc', 107, '00:04:28', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Mỹ Quyền', 108, '00:03:00', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Hồi Kết', 109, '00:04:34', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Lâu Lâu Nhắc Lại', 110, '00:04:30', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chưa Quên Người Yêu Cũ', 111, '00:05:02', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Không Nên Thật Lòng', 112, '00:03:45', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Đừng Bỏ Lỡ', 112, '00:02:46', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Bước Qua Tổn Thương Có Dễ Dàng', 112, '00:04:51', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chiếc Lá Mùa Đông', 112, '00:03:59', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Những Lời Dối Gian', 112, '00:03:08', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Không Nên Thật Lòng', 112, '00:03:45', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Từng Cho Nhau', 113, '00:04:23', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chuyến Xe Cuộc Đời', 114, '00:04:46', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Sau Này Chúng Ta Giàu', 115, '00:04:19', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Em Lấy Chồng', 116, '00:04:16', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chạy Về Nơi Phía Anh', 117, '00:03:01', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Suy Nghĩ Trong Anh', 118, '00:04:23', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Hiện Đại', 119, '00:03:52', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Khác Biệt', 120, '00:05:21', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Không Phải Anh Đúng Không', 121, '00:03:37', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Yêu Lại Từ Đầu', 122, '00:03:27', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Không Yêu Cũng Đừng Làm Bạn', 123, '00:04:43', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Cuối Cùng', 123, '00:04:39', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Ngại Yêu', 123, '00:05:10', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Người Không Đáng', 123, '00:04:06', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Biết Nói Là Tại Sao', 123, '00:04:59', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Slower', 124, '00:03:55', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'NGƯỜI LẠ TRONG MƠ', 125, '00:03:30', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Em Có Hiểu Anh Không', 126, '00:03:19', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Ta Vẫn Nắm Tay Nhau', 127, '00:03:29', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chia Tay Đừng Làm Bạn', 128, '00:03:17', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Tiền Đâu Mua Được', 129, '00:04:15', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'emconnho ... ???', 130, '00:04:50', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Quan Tâm Em Mỗi Ngày', 131, '00:04:07', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Tình Yêu Ngủ Quên', 132, '00:02:58', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'I Love You So Much', 133, '00:04:09', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Người Thương', 134, '00:04:42', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Yêu Em Rất Nhiều', 135, '00:04:30', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chút Nắng Chút Mưa', 136, '00:04:50', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Tìm Em Trong Đêm', 136, '00:03:48', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Em Đến', 136, '00:04:11', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Feel Your Love', 136, '00:05:07', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Vì Anh Có Em', 136, '00:03:44', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chỉ Có Thể Là Tình Yêu', 136, '00:04:01', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'EZ Papa', 137, '00:03:47', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Forget About Her', 138, '00:03:42', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Em Không Lẻ Loi', 139, '00:03:57', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Làm gì phải Hốt', 140, '00:03:09', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'LUS', 141, '00:03:16', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Thằng Điên', 142, '00:03:56', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Đã Lỡ Yêu Em Nhiều', 143, '00:04:21', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Bâng Khuâng', 144, '00:04:21', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Crying Over You', 144, '00:05:39', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Cuộc Gọi Cuối (Last Call)', 144, '00:04:37', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Lời Nói Dối Chân Thật', 144, '00:04:06', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Người Nào Đó', 144, '00:03:58', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Thời Gian Sẽ Trả Lời', 144, '00:04:02', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Forever Alone', 144, '00:03:59', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Vụt Tan', 144, '00:03:12', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Real Love', 144, '00:03:36', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'She Neva Knows', 144, '00:04:49', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Xin Anh Đừng', 144, '00:03:51', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Imma Heartbreaker', 144, '00:04:46', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Bật Khóc', 144, '00:03:51', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Where''s Mah Name', 144, '00:04:29', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Little Love (But No Limit)', 145, '00:04:11', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Anh Là Ngoại Lệ Của Em', 146, '00:03:09', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Phiêu Nhịp Thở', 147, '00:03:19', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'ThichThich', 148, '00:04:02', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Missing You', 149, '00:04:03', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Shine It Now - Thích Gì Làm Nấy', 150, '00:02:21', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Anh Là Ai', 151, '00:04:17', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Mặt Trời Của Em', 152, '00:04:09', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Crush On You', 153, '00:03:13', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Đẩy Xe Bò', 154, '00:02:46', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Vũ Trụ Có Anh', 155, '00:03:42', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Mùa Thu Cho Em', 156, '00:03:35', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Dư Âm', 156, '00:04:03', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Nắng Chiều', 156, '00:04:26', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Hoa Dại', 156, '00:03:40', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Hẹn Em Kiếp Sau', 156, '00:03:09', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Mẹ Từ Bi', 157, '00:05:53', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Nghìn Mắt Nghìn Tay', 157, '00:05:36', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Lạy Phật Quan Âm', 157, '00:04:51', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chú Đại Bi', 157, '00:03:51', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Liên Hoa', 157, '00:04:29', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Thích Ca Mâu Ni Phật', 157, '00:05:07', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Tinh Túy Bát Nhã Ba La Mật Đa', 157, '00:07:12', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Thương Về Miền Trung', 158, '00:04:36', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chờ Người', 158, '00:05:03', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chiều Nước Lũ', 158, '00:03:01', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Mây Chiều', 158, '00:05:35', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Gánh Chè Đêm Của Mẹ', 158, '00:05:34', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Đèn Khuya', 158, '00:04:44', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Nghĩa Mẹ Tình Cha', 158, '00:05:37', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Khúc Ca Ngày Mùa', 158, '00:04:25', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Bà Năm', 159, '00:04:40', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Hành Trình Trên Đất Phù Sa', 159, '00:04:48', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Bài Ca Đất Phương Nam', 159, '00:05:19', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chị Đi Tìm Em', 159, '00:05:48', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Quê Em Mùa Nước Lũ', 159, '00:05:34', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Áo Mới Cà Mau', 159, '00:03:51', N'')


INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Một Ngày Chẳng Nắng', 160, '00:03:13', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Kìa Bóng Dáng Ai', 161, '00:02:44', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Nai Vàng', 162, '00:03:44', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Độ Tộc 2', 163, '00:03:21', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Nói Dối', 164, '00:03:19', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Lạy Ông Lạy Bà', 165, '00:02:57', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'2 Phút Hơn', 166, '00:02:33', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chủ nhật boy', 167, '00:03:00', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'ưng quá chừng', 168, '00:01:22', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Shay Nắng', 169, '00:03:28', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'hai mươi hai (22)', 170, '00:03:59', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'thay mọi cô gái yêu anh', 171, '00:03:35', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Nói Hoặc Không Nói', 172, '00:03:45', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'từ thích thích thành thương thương', 173, '00:03:24', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Em Bé', 174, '00:03:12', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'dreAMEE (Intro)', 175, '00:00:40', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Anh Nhà Ở Đâu Thế (Solo Version)', 175, '00:03:36', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'yêu thì yêu không yêu thì yêu', 175, '00:03:10', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Đen Đá Không Đường (Remastered)', 175, '00:03:01', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Mama Boy', 175, '00:03:24', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Trời Giấu Trời Mang Đi (Solo Version)', 175, '00:04:14', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Ex''s Hate Me (Part 2)', 175, '00:03:37', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Sao Anh Chưa Về Nhà (Remastered)', 175, '00:04:04', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Xuân, Hạ, Thu, Đông Rồi Lại Xuân', 175, '00:04:51', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'G9 (Outro)', 175, '00:01:29', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Sao Anh Chưa Về Nhà', 176, '00:04:07', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Trời Giấu Trời Mang Đi', 177, '00:04:18', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Đen Đá Không Đường', 178, '00:03:02', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Anh Nhà Ở Đâu Thế', 179, '00:03:37', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'tình yêu có nghĩa là gì?', 180, '00:02:14', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'người đẹp ngủ', 180, '00:03:36', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'người điên', 180, '00:02:28', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'kho báu đánh rơi (ft. GREY D)', 180, '00:03:20', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'ái', 180, '00:01:07', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'làm lành chữa tình', 180, '00:03:26', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'thế giới thần tiên', 180, '00:02:51', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'những đốm sáng', 180, '00:04:03', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'nữ siêu anh hùng', 180, '00:03:32', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'ghệ iu giấu của em ơi', 180, '00:03:26', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'nếu lúc đó', 180, '00:04:25', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'kết thúc = mở đầu', 180, '00:00:57', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Gái Độc Thân', 181, '00:03:12', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chú Chó Trên Ô-tô', 182, '00:03:13', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Mặc Sự Đời!', 183, '00:03:16', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Tình Yêu Bận Bịu', 184, '00:03:12', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Kết Thúc Bắt Đầu', 185, '00:04:21', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Từ Ngày Em Đến', 186, '00:03:57', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'2 Ngày 1 Đêm', 187, '00:03:20', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chạy Khỏi Thế Giới Này', 188, '00:04:15', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Thức Giấc', 189, '00:04:29', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Gác Lại Âu Lo', 190, '00:04:43', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Nước Mắt Em Lau Bằng Tình Yêu Mới', 191, '00:04:46', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Thanh Xuân', 192, '00:03:41', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Một Nhà', 193, '00:03:06', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Intro', 194, '00:01:24', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Ném Câu Yêu Vào Không Trung', 194, '00:03:56', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Đôi Mươi', 194, '00:04:21', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Đoạn Kết Mới', 194, '00:04:55', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Nắng Thủy Tinh', 195, '00:04:01', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Tôi Muốn Làm Cái Cây', 196, '00:04:59', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Về Nghe Mẹ Ru', 197, '00:03:44', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Yêu Xa Hóa Gần', 198, '00:03:07', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Mùa Hè Bất Tận', 199, '00:05:09', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Nàng Thơ', 200, '00:04:14', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Thói Quen', 200, '00:04:31', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chia Tay', 200, '00:04:40', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Vì Một Câu Nói', 200, '00:04:53', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Ngủ Đi Để Thấy Nhau Còn Hồn Nhiên', 200, '00:05:51', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Bụi', 200, '00:04:39', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Nửa Thập Kỷ', 200, '00:05:20', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Bữa Tiệc Của Giác Quan', 200, '00:04:11', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Về Nhà', 200, '00:04:57', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chẳng Nói Nên Lời', 201, '00:05:28', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chờ Anh Nhé', 201, '00:05:22', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Có Những Mùa Đông', 201, '00:05:32', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Đi Đâu Để Thấy Hoa Bay', 201, '00:05:06', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Đôi Lời', 201, '00:03:52', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Mùa Viết Tình Ca (Acapella)', 201, '00:02:48', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Yếu Đuối', 201, '00:05:23', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Cuộc gọi về nhà', 202, '00:03:50', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Có đau thì đau một mình', 203, '00:03:31', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'7 tỷ người, tìm thấy anh rồi', 204, '00:03:40', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Tự Sự', 205, '00:04:17', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Em Hát Ai Nghe', 206, '00:04:36', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Khi Em Lớn', 207, '00:03:48', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chân Ái', 208, '00:04:23', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chẳng Ai Đến Thế Giới Này Để Cô Đơn', 209, '00:05:33', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Mẹ Hiểu Con Không', 210, '00:04:58', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Yêu Mấy Cũng Đừng Quay Lại', 211, '00:05:03', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Anh Bước Ra Từ Manga', 212, '00:05:26', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Phai Nhòa Cảm Xúc', 213, '00:04:18', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Không Muốn Yêu Lại Càng Say Đắm', 214, '00:05:31', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Yêu Người Không Thể Yêu', 215, '00:04:51', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Cô Đơn Không Muốn Về Nhà', 216, '00:03:15', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Đừng Lo Anh Đợi Mà', 217, '00:04:32', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Một Bước Yêu Vạn Dặm Đau', 218, '00:04:59', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Day Dứt Nỗi Đau', 219, '00:04:59', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Lặng Lẽ Tổn Thương', 219, '00:04:19', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Tìm Được Nhau Khó Thế Nào', 219, '00:04:30', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Bức Tranh Từ Nước Mắt', 219, '00:04:20', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Lắng Nghe Nước Mắt', 219, '00:05:24', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Day Dứt Nỗi Đau', 219, '00:04:59', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Phải Chi Lúc Trước Anh Sai', 220, '00:04:08', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chỉ Có Một Người Để Yêu Trên Thế Gian', 220, '00:04:46', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Marry Me', 220, '00:04:24', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Gần', 220, '00:04:39', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Em Đồng Ý (I Do)', 221, '00:03:23', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Quá Khứ Đôi, Hiện Tại Đơn', 222, '00:05:11', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Ngày Đầu Tiên', 223, '00:03:29', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Người Ơi Người Ở Đừng Về', 224, '00:03:20', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Hơn Cả Yêu', 225, '00:04:16', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Hết Thương Cạn Nhớ', 226, '00:04:43', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Yêu Được Không', 227, '00:05:32', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Còn Yêu, Đâu Ai Rời Đi', 228, '00:05:41', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Vỡ', 229, '00:04:05', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Ta Còn Yêu Nhau', 230, '00:03:27', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Ánh Nắng Của Anh', 231, '00:04:24', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Cũng Đành Thôi', 232, '00:04:33', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Thiên Tài', 233, '00:02:57', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Là Mây Trên Bầu Trời Của Ai Đó', 234, '00:04:37', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Đau Nhất Là Lặng Im', 235, '00:04:46', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chạy Về Khóc Với Anh', 236, '00:03:44', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Anh Luôn Là Lý Do', 237, '00:03:42', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Em Không Sai Chúng Ta Sai', 238, '00:04:52', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Có Tất Cả Nhưng Thiếu Anh', 239, '00:05:34', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chạm Đáy Nỗi Đau', 240, '00:04:53', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Mình Chia Tay Đi', 241, '00:04:05', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Ghen', 242, '00:04:07', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Sau Tất Cả', 243, '00:03:55', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Lạc Nhau Có Phải Muôn Đời', 244, '00:04:43', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chạm Gần Thêm Thương', 245, '00:03:27', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Vẽ Đường Cong', 246, '00:02:55', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Có Không Giữ Mất Đừng Tìm', 247, '00:03:36', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Sáng Mắt Chưa?', 248, '00:03:28', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Lớn Rồi Còn Khóc Nhè', 249, '00:03:31', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Người Ta Có Thương Mình Đâu', 250, '00:03:48', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Ngồi Hát Đỡ Buồn', 251, '00:03:15', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Making Money', 252, '00:03:38', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Thật Bất Ngờ', 252, '00:03:33', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Muốn Khóc Thật To', 253, '00:04:00', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Tìm', 254, '00:04:12', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Vẽ', 255, '00:04:17', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Bốn Chữ Lắm', 256, '00:04:21', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Đông', 257, '00:03:49', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Đưa Em Đi Khắp Thế Gian', 258, '00:04:34', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'vâng anh đi đi (liu riu version)', 259, '00:03:39', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'em bỏ hút thuốc chưa? (liu riu version)', 259, '00:03:51', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'nằm ngủ emru', 259, '00:04:15', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'drama queen (liu riu version)', 259, '00:04:37', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'từ chối nhẹ nhàng thôi (liu riu version)', 259, '00:03:46', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'chiếc hộp', 259, '00:03:36', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'em bỏ hút thuốc chưa?', 260, '00:03:36', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Một Cú Lừa', 260, '00:03:29', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'từ chối nhẹ nhàng thôi', 260, '00:04:07', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Một Cú Lừa (Đu Đưa Version)', 260, '00:03:44', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Đi Đu Đưa Đi', 261, '00:03:40', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chuyện Cũ Bỏ Qua', 262, '00:03:18', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Bùa Yêu', 263, '00:04:02', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chị Ngã Em Nâng', 264, '00:03:46', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Nói Thương Nhau Thì Đừng Làm Trái Tim Em Đau', 265, '00:04:38', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Bao Giờ Lấy Chồng?', 266, '00:03:40', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Gửi Anh Xa Nhớ', 267, '00:04:16', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Rằng Em Mãi Ở Bên', 268, '00:03:43', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Sâu Trong Em', 268, '00:03:58', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Giúp Em Trả Lời Những Câu Hỏi', 269, '00:04:49', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Những Đêm Lặng Câm', 269, '00:04:00', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Mình Yêu Nhau Đi', 270, '00:03:23', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chỉ Là Em Giấu Đi', 271, '00:04:29', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Nếu Hạnh Phúc Không Phải Em', 271, '00:05:21', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Khoảng Lặng', 271, '00:03:44', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Mong Manh', 271, '00:05:13', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Ngày Gió Ngừng Trôi', 271, '00:04:30', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Mình Yêu Nhau Để Làm Gì', 271, '00:04:23', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Em Không Làm Được Đâu', 271, '00:04:53', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Vẫn', 271, '00:05:38', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Có Khi Nào Rời Xa', 271, '00:04:25', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Có Lẽ Em', 271, '00:04:28', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Em Muốn', 271, '00:04:38', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Tìm X', 272, '00:03:04', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Late Blooming Flower', 273, '00:00:48', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Cà Phê', 273, '00:03:11', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Anh Qua Đây Đi', 273, '00:03:20', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Phải Lòng Anh', 273, '00:03:47', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Watching The Stars', 273, '00:01:32', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Ngắm Sao (Dear Miniacs)', 273, '00:03:23', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Phải Lòng Anh (Dream Ver.)', 273, '00:03:54', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Hít Vào Thở Ra', 274, '00:03:14', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Trên Tình Bạn Dưới Tình Yêu', 275, '00:03:19', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Đừng Yêu Nữa, Em Mệt Rồi', 276, '00:04:41', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Vì Yêu Cứ Đâm Đầu', 277, '00:03:51', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Em Mới Là Người Yêu Anh', 278, '00:03:49', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Có Em Chờ', 279, '00:03:54', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chưa Bao Giờ Mẹ Kể', 280, '00:04:19', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Hôn Anh', 281, '00:03:54', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Gọi Tên Em', 282, '00:03:49', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Make Me Feel', 283, '00:03:36', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Overture', 283, '00:01:46', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Men Cry (ft. Gonzo, Nomovodka)', 283, '00:04:13', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Hit Me Up', 283, '00:04:28', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Taste Of Love', 283, '00:03:43', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Lift (ft. $A MILO)', 283, '00:03:22', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Don''t Break My Heart', 284, '00:03:57', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Cho Mình Em	', 285, '00:03:26', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'ToGetHer', 286, '00:02:29', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'021', 287, '00:03:12', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Bigcityboi', 288, '00:03:22', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'OK', 289, '00:02:34', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Quên Anh Đi', 290, '00:03:46', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Sao Cũng Được', 291, '00:04:28', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'SOFAR', 292, '00:03:25', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Anh Nhớ Ra (Feat. Trang)', 293, '00:04:36', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Cô Ta', 293, '00:03:45', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chậm Lại', 293, '00:04:12', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Nhường Lại Em (Feat. Phúc Du)', 293, '00:03:34', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Cuộc Đối Thoại Không Hồi Kết (Feat. Mạc Mai Sương)', 293, '00:04:35', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Chợt Nhìn Nhau', 293, '00:03:00', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Sau Chia Tay Ta Còn Gì?', 293, '00:04:41', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Happy For You (Lukas Graham)', 294, '00:03:47', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Bước Qua Nhau', 295, '00:04:18', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Bước Qua Mùa Cô Đơn', 296, '00:04:39', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Đã Từng Là', 297, '00:04:21', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Một Giấc Mơ', 298, '00:03:48', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Mùa Hè Của Em', 299, '00:04:18', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Xin Phép Được Cô Đơn', 300, '00:05:10', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Có thể là tại sao?', 301, '00:02:29', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Lạ Lùng', 302, '00:04:22', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Đông Kiếm Em', 303, '00:04:06', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Nấu ăn cho em', 304, '00:04:06', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Luôn yêu đời', 305, '00:03:57', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Ai muốn nghe không', 306, '00:04:58', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Mang Tiền Về Cho Mẹ', 307, '00:06:40', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Trốn Tìm', 308, '00:04:12', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Đi Về Nhà', 309, '00:03:20', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Trời hôm nay nhiều mây cực!', 310, '00:04:12', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'một triệu like', 311, '00:04:21', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Lối Nhỏ', 312, '00:04:12', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'hai triệu năm', 313, '00:03:37', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Bài Này Chill Phết', 314, '00:04:33', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Mười Năm', 315, '00:04:06', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Đố em biết anh đang nghĩ gì', 316, '00:04:06', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Anh Đếch Cần Gì Nhiều Ngoài Em', 317, '00:03:38', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Đưa Nhau Đi Trốn', 318, '00:04:00', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'CONG', 319, '00:01:16', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'1 Cọng Tóc Mai', 319, '00:03:17', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'906090', 319, '00:03:29', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Like This Like That', 319, '00:03:45', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Nếu Anh Là Em', 319, '00:04:33', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Bồng Bềnh', 319, '00:04:06', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Khá Khen', 319, '00:03:06', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'AM I CLEAR?!', 319, '00:03:11', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Trên Chuyến Xe Lên Đà Lạt Chiều Nay', 320, '00:03:53', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Từ Những Thói Quen', 320, '00:04:14', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Mình Yêu Đến Đây Thôi', 320, '00:04:46', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Trên Chuyến Xe Lên Đà Lạt Chiều Nay', 320, '00:03:53', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Em Đã Có Người Mới', 321, '00:03:20', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Ngày Tận Thế', 322, '00:03:52', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Thì Em Vẫn Thế', 323, '00:04:11', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Phút Giây Tuyệt Vời', 324, '00:03:40', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Có Ai Thương Em Như Anh (#CATENA)', 325, '00:03:51', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Hôm Nay Tôi Cô Đơn Quá', 326, '00:03:50', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Em Không Là Duy Nhất', 327, '00:04:41', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Bèo Dạt Mây Trôi (OST Người Vợ Cuối Cùng)', 328, '00:02:17', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Góc Tối (OST Người Vợ Cuối Cùng)', 328, '00:02:14', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Nếu Nỗi Buồn Là Một Bông Hoa', 329, '00:05:44', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Hơn Em Chỗ Nào', 330, '00:04:56', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Việt Nam Trong Tôi Là (Tí Nâu)', 331, '00:05:06', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Không Sao Mà, Em Đây Rồi (Thong Dong Mà Hát)', 332, '00:03:04', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Tình Yêu Chậm Trễ (Thong Dong Mà Hát)', 332, '00:03:32', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Buồn Thì Cứ Khóc Đi (Thong Dong Mà Hát)', 332, '00:03:01', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Tình Ca (Thong Dong Mà Hát)', 332, '00:03:03', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Phiến Lá Tĩnh Lặng', 333, '00:05:08', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Giấc Mơ Trưa', 334, '00:05:42', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Mùa Hạ Ơi Xa Rồi', 335, '00:05:01', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Những Đứa Con Xa Nhà', 336, '00:06:31', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Mình Cùng Nhau Đóng Băng', 337, '00:04:12', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Nàng Thơ Xứ Huế', 338, '00:04:28', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Cha Và Con Gái', 339, '00:06:07', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Xe Đạp', 340, '00:04:44', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Intro', 341, '00:02:33', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Sinh Nhật Của Xinh Nhất', 341, '00:03:00', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Nước Mắt Đâu Thể Rơi Được', 341, '00:03:33', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'All Night', 341, '00:02:55', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Late Night Ride', 341, '00:03:52', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Vẫn', 342, '00:03:58', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Truy Lùng Bảo Vật', 343, '00:04:51', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Từ A Đến Z', 344, '00:03:17', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Bao Giờ Lấy Vợ', 345, '00:03:12', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Bao Giờ Em Đổ?', 346, '00:01:40', N'')

INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Stay Cool 2', 347, '00:02:29', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Người Tình Mùa Đông (DTAP)', 348, '00:03:42', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Stay Cool', 349, '00:02:43', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'INTRO', 350, '00:01:00', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Buông', 350, '00:02:29', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Em Là', 350, '00:03:17', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Kill Me', 350, '00:03:49', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Quên Anh Đi', 350, '00:04:06', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'MONOlogue', 350, '00:01:04', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Anh Không Thể', 350, '00:03:40', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Do You', 350, '00:03:38', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Co Nuong Ahhhh~', 350, '00:00:56', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'Waiting For You', 350, '00:04:26', N'')
INSERT INTO Song(title, albumID, duration, filepath) VALUES (N'L.I.E', 350, '00:03:46', N'')


































